export const DOC_FETCH_DOCUMENTS_DB_SUCCESS = 'DOC_FETCH_DOCUMENTS_DB_SUCCESS';
export const DOC_FETCH_DOCUMENTS_DB_LOADING = 'DOC_FETCH_DOCUMENTS_DB_LOADING';
export const DOC_FETCH_DOCUMENTS_DB_FAIL = 'DOC_FETCH_DOCUMENTS_DB_FAIL';

export const DOC_QUERY_DOCUMENTS_SCHOLAR_SUCCESS =
  'DOC_QUERY_DOCUMENTS_SCHOLAR_SUCCESS';
export const DOC_QUERY_DOCUMENTS_SCHOLAR_FAIL =
  'DOC_QUERY_DOCUMENTS_SCHOLAR_FAIL';
export const DOC_QUERY_DOCUMENTS_SCHOLAR_LOADING =
  'DOC_QUERY_DOCUMENTS_SCHOLAR_LOADING';

export const DOC_QUERY_DOCUMENTS_PUBMED_SUCCESS =
  'DOC_QUERY_DOCUMENTS_PUBMED_SUCCESS';
export const DOC_QUERY_DOCUMENTS_PUBMED_FAIL =
  'DOC_QUERY_DOCUMENTS_PUBMED_FAIL';
export const DOC_QUERY_DOCUMENTS_PUBMED_LOADING =
  'DOC_QUERY_DOCUMENTS_PUBMED_LOADING';

export const DOC_QUERY_DOCUMENT_INFO_PUBMED_SUCCESS =
  'DOC_QUERY_DOCUMENT_INFO_PUBMED_SUCCESS';
export const DOC_QUERY_DOCUMENT_INFO_PUBMED_FAIL =
  'DOC_QUERY_DOCUMENT_INFO_PUBMED_FAIL';
export const DOC_QUERY_DOCUMENT_INFO_PUBMED_LOADING =
  'DOC_QUERY_DOCUMENT_INFO_PUBMED_LOADING';

export const DB_FILTER_BY_DATE = 'DB_FILTER_BY_DATE';
export const DB_CLEAR_FILTER_BY_DATE = 'DB_CLEAR_FILTER_BY_DATE';

export const DB_UPDATE_VISUALIZATION_WITH_DOCS_SUCCESS =
  'DB_UPDATE_VISUALIZATION_WITH_DOCS_SUCCESS';
export const DB_UPDATE_VISUALIZATION_WITH_DOCS_FAIL =
  'DB_UPDATE_VISUALIZATION_WITH_DOCS_FAIL';
export const DB_UPDATE_VISUALIZATION_WITH_DOCS_LOADING =
  'DB_UPDATE_VISUALIZATION_WITH_DOCS_LOADING';

export const DB_SORT_DOCUMENTS_BY = 'DB_SORT_DOCUMENTS_BY';
export const DB_FILTER_DOCUMENTS = 'DB_FILTER_DOCUMENTS';

export const DB_UPDATE_GET_WORD_DISTANCE_SUCCESS =
  'DB_UPDATE_GET_WORD_DISTANCE_SUCCESS';
export const DB_UPDATE_GET_WORD_DISTANCE_FAIL =
  'DB_UPDATE_GET_WORD_DISTANCE_FAIL';
export const DB_UPDATE_GET_WORD_DISTANCE_LOADING =
  'DB_UPDATE_GET_WORD_DISTANCE_LOADING';
